### PR TITLE
Issue_609

### PR DESCRIPTION
**Pull request by jj105**
## issue
#609

### CODE REVIEW

**Comment by jj105** [comment]
I edited code but didn't have enough test since I don't have sample database.

If I the issue is fixed as you wish, there'll be no problem.
but if it isn't fixed yet, can you please give me sample db dump file so that I can test it on my machine?

I think fixing this issue will not exceed an hour once I have db dump file.
Thank you.

**Comment by shnizzedy** [comment]
> but if it isn't fixed yet, can you please give me sample db dump file so that I can test it on my machine?

Permissions are set at the applet level (that's the main purpose of the applet structure), so it would be a job to build an applet on one server and allow a user on a different server access. It would be much simpler for you to either [use the GUI to test your own local version](#use-the-gui) or [write a test](#write-a-test) to test your code. An overview of each option below.

### Use the GUI

1. Follow the [Requirements](https://github.com/ChildMindInstitute/mindlogger-app-backend#reqirements) and [Installation](https://github.com/ChildMindInstitute/mindlogger-app-backend#installation) instructions in the [README](https://github.com/ChildMindInstitute/mindlogger-app-backend/blob/master/README.rst) to get a local MongoDB instance connected to a local instance of Girder for MindLogger serving on [localhost:8080](http://localhost:8080). The terminal running `girderformindlogger serve` will echo live logs.
live logging in 
![8
terminal](https://user-images.githubusercontent.com/5974438/74677096-87427080-5185-11ea-8779-ad78723b55bc.gif)
2. Navigate to [admin.mindlogger.org](https://admin.mindlogger.org).
3. Choose `localhost (localhost:8080)` from the "Select Your Server" dropdown. Click "Continue."
create_account
4. Click "Create Account," and fill in the fields to create a new account. Click "Continue."
5. Click the ⊕ in the bottom right. Choose "MindLogger Demo" from the "Quick Add" links. Click "Add." Wait for the protocol to load and the applet to be created.
6. Once you get a success message (eg, `Your applet, reprolib:protocols/mindlogger-demo/mindlogger-demo_schema, has been successfully created. The applet's ID is applet/{applet_id}`, reload [admin.mindlogger.org](https://admin.mindlogger.org). Log in with the account you created in step 4. You'll see the applet that was just created.
7. Repeat steps 5 and 6
    1. Click the ⊕ in the bottom right. Choose "MindLogger Demo" from the "Quick Add" links. Click "Add." Wait for the protocol to load and the applet to be created.
    2. Once you get a success message (eg, `Your applet, reprolib:protocols/mindlogger-demo/mindlogger-demo_schema, has been successfully created. The applet's ID is applet/{applet_id}`, reload [admin.mindlogger.org](https://admin.mindlogger.org). Log in with the account you created in step 4.  You'll see the aplet that was just created.
8. Check if the applets have the same name.
"MindLogger Demo" ×2
The gif above is the outcome of following these steps on my local machine with the code from https://github.com/ChildMindInstitute/mindlogger-app-backend/pull/645/commits/8aabf5df1406f3f385bf9ed1db20107a2ecf1f26

### Write a test
The output of `GET /user/applets?role=coordinator&unexpanded=true` will be an Array of Objects in which `applet["http://www.w3.org/2004/02/skos/core#prefLabel"]["@value"]` will be the display name of an applet.

GET /user/applets?role=coordinator&unexpanded=true


A passing test to ensure that no duplicates exist would resolve #609.

**Comment by jj105** [comment]
Thank you for the info.
I'll recheck two issues.

**Comment by jj105** [comment]
Hi, Jon.
I tried to login https://admin.mindlogger.org as you told me, but it throws network error.
Did you meet similar case before?

**Comment by shnizzedy** [comment]
@jj105 Are you able to load http://localhost:8080?

**Comment by jj105** [comment]
Hi, Jon.
I fixed issue by allowing CORS in admin console.
I'll start checking issues now.

**Comment by shnizzedy** [comment]
superseded by #648

**Pull request closed without merging**
