### PR TITLE
:tractor: Routes

### PR DESCRIPTION
**Pull request by shnizzedy**
- New and updated routes:
  - `GET /activity`
  - `GET /response`
  - `POST /response/{applet}/{activity}`
- New and updated models:
  - Activity
  - Applet
  - Assignment
  - ResponseFolder
  - ResponseItem
- Update configuration
  - `requirements.txt`
  - logo
  - favicon

---

These changes will break [mindlogger-web](https://mindlogger-web.anisha.pizza). https://github.com/ChildMindInstitute/mindlogger-web/pull/37 should fix what this PR breaks.

### CODE REVIEW

**Comment by akeshavan** [comment]
This looks good to me when testing locally, but why are the Circle tests failing?

**Comment by akeshavan** [comment]
Oh, it would be nice if `/user/${user}/applets?role=${role}` return the applet `_id`s, so that we don't have to add the extra call on the frontend:
```javascript
api.getAppletFromURI({
        apiHost: this.apiHost,
        token: this.user.authToken.token,
        URI: this.appletUrl,
  }).then(...)```

**Comment by shnizzedy** [comment]
> This looks good to me when testing locally, but why are the Circle tests failing?

The Circle tests are the Girder classic tests that assume public users, which we do not have. I haven't updated the tests yet to match our changes (though I do have [a branch for that](https://github.com/ChildMindInstitute/mindlogger-app-backend/tree/%F0%9F%92%9A)).

**Comment by shnizzedy** [comment]
> Oh, it would be nice if `/user/${user}/applets?role=${role}` return the applet `_id`s, so that we don't have to add the extra call on the frontend:
> 
> ```js
> api.getAppletFromURI({
>         apiHost: this.apiHost,
>         token: this.user.authToken.token,
>         URI: this.appletUrl,
>   }).then(...)```
> ```

_Soon_ the _id will be included in the Applet Object. I was going to do that today, but it's 4:43 and I'm just now getting a chance to do my first-thing-email check.

**Pull request merged**
