### PR TITLE
Tests and bug fixes

### PR DESCRIPTION
**Pull request by akeshavan**
sorry for the extra commit (https://github.com/ChildMindInstitute/mindlogger-app-backend/commit/f01a3a099f262cfab6d073ffe0b0598dccd1523f) !! Maybe you can remove it, @shnizzedy ?

I'm adding a notebook with some tests, but I'm not able to add a new applet right now

### CODE REVIEW

**Comment by akeshavan** [comment]
see notebook rendered here: https://nbviewer.jupyter.org/github/ChildMindInstitute/mindlogger-app-backend/blob/03ed101ab699402b5b8d5e699e9b2f66b4d07653/backendTests.ipynb

**Comment by akeshavan** [comment]
# Plan

- [x] create a new user (userA)
- [x] get userA's applets and make sure the list is empty
- [x] userA creates an applet with an activity-set-url (url TBD)
- [ ] get userA's applets and make sure we have the applet they just created
- [ ] create userB
- [ ] userA invites userB to the applet
- [ ] make sure userB has an invite
- [ ] userB accepts their invite
- [ ] list userB's applets
- [ ] userA invites userC (by email) to the applet
- [ ] create userC with the same email
- [ ] check that userC has an invite
- [ ] accept userC's applet invite
- [ ] check userC's applets
- [ ] userA, B and C submit responses to each activity in the applet
- [ ] get responses for each user in the last 7 days
- [ ] user B removes the applet without removing data
- [ ] user C removes the applet AND removes data
- [x] delete userB and userC
- [ ] userA deactivites their applet
- [ ] delete userA

**Comment by akeshavan** [comment]
- [ ] refresh and applet
- [ ] add a schedule to an applet

**Comment by shnizzedy** [comment]
> sorry for the extra commit ([f01a3a0](https://github.com/ChildMindInstitute/mindlogger-app-backend/commit/f01a3a099f262cfab6d073ffe0b0598dccd1523f)) !! Maybe you can remove it, @shnizzedy ?

What do you mean extra? It looks like that fixes a bug for if the Applets collection doesn't exist yet when a particular method is first called.

[Here](https://github.com/ChildMindInstitute/mindlogger-app-backend/tree/89d4421466640bdb23f458fd4edbd76b0e9bc235)'s this branch without that commit if you really want it.

**Comment by akeshavan** [comment]
@shnizzedy ok fair enough! this PR then is a mix of bug fixes to the server and a notebook of tests :)

**Comment by akeshavan** [comment]
closing cause its merged already.

**Pull request closed without merging**
