### PR TITLE
issue_609

### PR DESCRIPTION
**Pull request by jj105**

### CODE REVIEW

**Comment by jj105** [comment]
Hi, Jon.
I edited code to fix issue_609.
but on my environment, it takes too long time (more than an hour) to create a new applet.
I think it loads too many resources.

**Comment by jj105** [comment]
Can you please tell me what should I do to make process of creating a new applet run faster?

**Comment by shnizzedy** [comment]
> Can you please tell me what should I do to make process of creating a new applet run faster?

It's [an open epic](https://github.com/ChildMindInstitute/mindlogger-app-backend/issues/613) and in my opinion, the current weakest link in the whole project. On my machine, it takes ~1‒2 seconds per JSON-LD document to load a protocol, so for testing I just choose smallish protocols, like [reproschema:protocols/mindlogger-demo/mindlogger-demo_schema](https://raw.githubusercontent.com/ReproNim/reproschema/master/protocols/mindlogger-demo/mindlogger-demo_schema), which still takes several minutes.

See also https://github.com/ChildMindInstitute/mindlogger-app-backend/pull/625#issuecomment-588437844

**Comment by shnizzedy** [comment]
We only have [~28% coverage](https://codecov.io/gh/ChildMindInstitute/mindlogger-app-backend) of the Python core in this codebase as of a8ba865, but I'd argue that's no reason not to include tests with new functionality.

> ### <a name="write-a-test">Write a test</a>
> The output of `GET /user/applets?role=coordinator&unexpanded=true` will be an Array of Objects in which `applet["http://www.w3.org/2004/02/skos/core#prefLabel"]["@value"]` will be the display name of an applet.
> 
> GET /user/applets?role=coordinator&unexpanded=true

― https://github.com/ChildMindInstitute/mindlogger-app-backend/pull/645#issuecomment-587105688

**Pull request closed without merging**
