### PR TITLE
update getAppletUsers function to return userId

### PR DESCRIPTION
**Pull request by jj105**
# update  applet/[:id]/users router to return userId value

### CODE REVIEW

**Comment by shnizzedy** [comment]
I disagree with this change.

I know I don't really have a horse in the race anymore, but a lot of effort was put into making everything work without anyone ever needing to see anyone's userId except their own. The idea of [profiles](https://github.com/ChildMindInstitute/mindlogger-app-backend#profile) was created to allow an identity airgap, so that a single user login could be used for multiple applets without managers of either applet knowing that the user is also a user of the the other.

Unless the product requirements have changed again in a way that user privacy is less of a concern, [I don't see why userIds should ever be exposed](https://github.com/ChildMindInstitute/mindlogger-app-backend/issues/153).

**Comment by jj105** [comment]
Hi, Jon.
Thanks for checking my PR.
The main reason I inserted userId is that frontend required this parameter.

**Comment by shnizzedy** [comment]
For what? I almost certainly vote for updating the frontend to use the profile instead of reverting to revealing the userId

**Comment by jj105** [comment]
Hi, Jon.
Thank you for giving us advice.
We noticed that we can remove userId field in the api response.
I really appreciate for your help.

**Pull request merged**
